version: '3.9'
services:
  spire:
    container_name: spire
    image: spire:local
    ports:
      - "8081:8081"
    expose:
      - '8081'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
  server01:
    container_name: server01
    image: mysql:local
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3301:3306"
    expose:
      - '3301'
    volumes:
       - ./config/server01/my.cnf:/etc/my.cnf
       - ./volumes/mysql/server01:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
  proxysql01:
    container_name: proxysql01
    image: proxysql:ssl
    ports:
      - "6032:6032"
      - "6033:6033"
    expose:
      - '6032'
      - '6033'
    volumes:
      - ./config/proxysql/proxysql.cnf:/etc/proxysql.cnf
      - ./volumes/proxysql/proxysql01:/var/lib/proxysql
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
